export const ENDPOINTS = {
  USER_PROFILE: "user/profile",
  USER_PROFILE_PASSWORD_UPDATE: "user/password",
  LOGIN: "auth/login",
  REGISTER_MAIL: "auth/signup",
  SEND_OTP: "auth/verify",
  SET_PASSWORD: "auth/set-password",
  FORGOT_PASSWORD: "auth/reset-password",
  VERIFY_RESET_PASSWORD: "auth/verify-reset-password",
  ASSISTANT: "assistant/list",
  CLONE_AGENT: "clone",
  CALL_LIST: "call/list",
  CALL_LIST_BY_ID: "call/assistant",
  CALL_DETAILS_BY_ID: "call",
  KNOWLEDGE_BASE_DOCUMENTS_LIST: "file/list",
  KNOWLEDGE_BASE_DOCUMENTS_UPLOAD: "file/upload",
  KNOWLEDGE_BASE_DOCUMENTS: "file",
  AGENT_DATA: "assistant/",
  PHONE_NUMBER_LIST: "phone_number/list",
  PHONE_NUMBER: "phone_number",
  PHONE_NUMBER_AVAILABLE: "phone_number/available",
  PHONE_NUMBER_BUY: "phone_number/buy",
  ACTION : "action/",
  ONBOARDING:"company/onboarding/complete",
  ONBOARDING_GET:"company",
  COMPANY_STATS:"company/stats",
  GOOGLE_AUTH:"calendar/connect/google",
  OUTLOOK_AUTH:"calendar/connect/outlook",
  ZOHO_AUTH:"integrations/zoho/connect",
  CREATE_ACTION:"action/",
  GOOGLE_CALENDAR_LIST:"booking/list",
  GOOGLE_SINGLE_CALENDAR_LIST:"booking/",
  ACTIONS:"action/list",
  CALENDAR_LIST:"calendar/list",
  CALENDAR_FETCH_ALL_LATEST:"calendar/fetch",
  CALENDAR_REMOVE:"calendar/accounts/",
  CONNECT_CALENDAR:"calendar/connect",
  CALENDAR:"calendar/",
  TEAM_INVITE:"member/invite",
  TEAM_MEMBER:"member",
  GET_TEAM_INVITATION:"member/invitations",
  GET_TEAM_INVITATION_PENDING:"member/invitations",
  ACCEPT_TEAM_INVITATION:"member/accept-invitation",
  COMPANY_SWITCH : "company/credentials",
  STRIPE_PLAN : "billings/plan",
  STRIPE_CHECKOUT : "billings/checkout",
  STRIPE_SUBSCRIPTION : "billings/subscription/",
  ACTIVE_SUBSCRIPTION : "billings/subscription",
  CAMPAIGN_LIST : "campaign/list",
  CAMPAIGN : "campaign",
  CAMPAIGN_CREATE : "campaign/create",
  CAMPAIGN_DOCUMENT_UPLOAD: "campaign/upload-contacts",
  INVOICE_LIST : "billings/invoice",
  ZOHO_INTEGRATION:"integrations/zoho",
  USAGE_LIST:"billings/usage",
  FOLDER_LIST:"folder",
  FOLDER_VARIABLE:"folder/",
  SMTP_CONFIG:"accounts/smtp",
 
};
